defaults:
  - debias: st
  - compress: kt
  - cache: dummy
  - _self_

problem:
  folder: '../../../riabiz_data/Cardiac/Tempered_posterior/seed_1'
  gold_folder: '../reference'
  point_file: theta.csv
  score_file: grad.csv
  meta_file: meta.yaml
  burnin: none
  remove_burnin: false
  fmt: h5
  point_score_file: 'points_scores_nowarmup.h5'
  num_sample: 65536
  seed: 1

out_size: 'n**0.5'

jax:
  platforms: cuda
  enable_x64: true
