name: Build and upload to PyPI

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Build package
    runs-on: macos-latest
    # upload to PyPI on every tag starting with 'v' 
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel Cython numpy auditwheel
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
  pypi-publish:
    needs: build
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/goodpoints
    permissions:
      id-token: write
    # upload to PyPI on every tag starting with 'v' 
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks artifacts into dist/
          name: dist
          path: dist
      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
